### PR TITLE
Add gulp-gh-pages util

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

This allows a quick and easy deploy to gh-pages branch from the `_site` folder using the command `gulp deploy`.

The gh-pages branch is relative to the repository.

## QA

Fork this repo; run `gulp` to build out all site assets, then run `gulp deploy`

A demo should now be running at;

`http://YOUR-GITHUB-USERNAME.github.io/cloud-init/`

### CODE REVIEW

**Comment by anthonydillon** [comment]
Worked but missing styles: http://anthonydillon.github.io/cloud-init/

**Comment by anthonydillon** [comment]
Am I missing a step? QA steps:
```bash
npm i
gulp
gulp deploy
```

**Comment by barrymcgee** [comment]
@anthonydillon Pull and try again now?

**Comment by barrymcgee** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DmBpiidA&#x2F;27-finish-demo"> Finish demo</a>

**Comment by anthonydillon** [comment]
Awesome, thanks :+1:

**Pull request merged**
